/**
 * Mock Contact Spheres for Affiliate Networking
 */

import type { ContactSphereDoc } from "../schema";
import { daysAgo } from "./affiliates";

export const mockContactSpheres: ContactSphereDoc[] = [
  {
    id: "sphere-001", affiliateId: "aff-001", sphereName: "Manufacturing Excellence Network",
    members: [
      { name: "Tom Bradley", profession: "Commercial Banker", company: "First Citizens Bank" },
      { name: "Rachel Kim", profession: "Manufacturing Attorney", company: "Smith Anderson" },
      { name: "James Wilson", profession: "Industrial Real Estate", company: "CBRE" },
      { name: "Maria Santos", profession: "HR Consultant", company: "Insperity" },
      { name: "Kevin O'Brien", profession: "Business Insurance", company: "Marsh McLennan" },
      { name: "Diana Foster", profession: "CPA", company: "Cherry Bekaert" },
      { name: "Steve Park", profession: "IT Services", company: "Logically" },
      { name: "Nancy Chen", profession: "Marketing Agency", company: "Luquire George Andrews" },
      { name: "Paul Martinez", profession: "Equipment Financing", company: "Wells Fargo" },
      { name: "Linda Thompson", profession: "Executive Recruiter", company: "Korn Ferry" },
    ],
    topProfessionsNeeded: [
      { profession: "Environmental Consultant", description: "For EPA compliance and sustainability initiatives" },
      { profession: "Cybersecurity Specialist", description: "For OT/IT security in manufacturing" },
      { profession: "Grant Writer", description: "For manufacturing modernization grants" },
    ],
    commitment: "I commit to making 2 introductions per month to help fill your contact sphere",
    createdAt: daysAgo(170), updatedAt: daysAgo(5),
  },
  {
    id: "sphere-002", affiliateId: "aff-002", sphereName: "Quality & Compliance Circle",
    members: [
      { name: "Jennifer Adams", profession: "Environmental Consultant", company: "ERM" },
      { name: "Robert Lee", profession: "Safety Consultant", company: "Safex" },
      { name: "Michelle Brown", profession: "Manufacturing Attorney", company: "Brooks Pierce" },
      { name: "David Kim", profession: "Business Insurance", company: "Lockton" },
      { name: "Susan White", profession: "HR Outsourcing", company: "ADP" },
      { name: "Chris Taylor", profession: "Commercial Banker", company: "Bank of America" },
      { name: "Angela Martinez", profession: "CPA", company: "Dixon Hughes Goodman" },
      { name: "Brian Johnson", profession: "IT Security", company: "Palo Alto Networks" },
      { name: "Karen Davis", profession: "Training Provider", company: "Skillsoft" },
      { name: "Mark Wilson", profession: "Equipment Dealer", company: "Grainger" },
    ],
    topProfessionsNeeded: [
      { profession: "Lean Consultant", description: "To complement quality with operational efficiency" },
      { profession: "Automation Engineer", description: "For quality control automation" },
      { profession: "Supply Chain Consultant", description: "For supplier quality management" },
    ],
    commitment: "Happy to introduce you to my network of 200+ certified companies",
    createdAt: daysAgo(190), updatedAt: daysAgo(10),
  },
  {
    id: "sphere-003", affiliateId: "aff-003", sphereName: "Operational Excellence Partners",
    members: [
      { name: "Carlos Mendez", profession: "Six Sigma Consultant", company: "Independent" },
      { name: "Amy Johnson", profession: "Change Management", company: "Prosci" },
      { name: "Derek Williams", profession: "Industrial Engineer", company: "Kimley-Horn" },
      { name: "Patricia Lee", profession: "Manufacturing CPA", company: "RSM" },
      { name: "John Smith", profession: "Commercial Lender", company: "Truist" },
      { name: "Rebecca Taylor", profession: "HR Consultant", company: "Mercer" },
      { name: "Michael Brown", profession: "Safety Manager", company: "Cintas" },
      { name: "Laura Garcia", profession: "Environmental", company: "Terracon" },
      { name: "Steven Clark", profession: "IT Consultant", company: "Accenture" },
      { name: "Nicole Adams", profession: "Marketing", company: "Wray Ward" },
    ],
    topProfessionsNeeded: [
      { profession: "Quality Consultant", description: "For ISO certification support" },
      { profession: "Workforce Trainer", description: "For lean training programs" },
      { profession: "Digital Transformation", description: "For Industry 4.0 lean integration" },
    ],
    commitment: "Will actively refer lean opportunities and make introductions monthly",
    createdAt: daysAgo(140), updatedAt: daysAgo(3),
  },
  {
    id: "sphere-004", affiliateId: "aff-004", sphereName: "Automation & Technology Alliance",
    members: [
      { name: "Richard Chen", profession: "Controls Engineer", company: "Rockwell Automation" },
      { name: "Sandra Miller", profession: "Machine Vision", company: "Cognex" },
      { name: "Timothy Brown", profession: "Robot Integrator", company: "FANUC" },
      { name: "Elizabeth Jones", profession: "PLC Programmer", company: "Siemens" },
      { name: "Andrew Wilson", profession: "Electrical Contractor", company: "Miller Electric" },
      { name: "Catherine Lee", profession: "Equipment Finance", company: "CIT" },
      { name: "Daniel Martinez", profession: "Industrial Supplies", company: "Fastenal" },
      { name: "Jessica Taylor", profession: "Safety Systems", company: "Pilz" },
      { name: "Matthew Davis", profession: "CAD Services", company: "Autodesk" },
      { name: "Stephanie White", profession: "Technical Recruiter", company: "Aerotek" },
    ],
    topProfessionsNeeded: [
      { profession: "Process Engineer", description: "To identify automation opportunities" },
      { profession: "Lean Consultant", description: "For pre-automation process optimization" },
      { profession: "Workforce Trainer", description: "For robot operator training" },
    ],
    commitment: "I refer all non-automation needs to my sphere and expect reciprocity",
    createdAt: daysAgo(210), updatedAt: daysAgo(8),
  },
  {
    id: "sphere-005", affiliateId: "aff-005", sphereName: "Workforce Development Network",
    members: [
      { name: "Amanda Roberts", profession: "Community College Dean", company: "Forsyth Tech" },
      { name: "Gregory Thompson", profession: "Staffing Agency", company: "Manpower" },
      { name: "Diane Wilson", profession: "Career Counselor", company: "NCWorks" },
      { name: "Frank Garcia", profession: "Benefits Consultant", company: "Gallagher" },
      { name: "Helen Martinez", profession: "Payroll Services", company: "Paychex" },
      { name: "Ivan Petrov", profession: "Immigration Attorney", company: "Ogletree Deakins" },
      { name: "Janet Lee", profession: "Workers Comp", company: "Employers" },
      { name: "Kenneth Brown", profession: "Safety Training", company: "NSC" },
      { name: "Laura Adams", profession: "LMS Provider", company: "Cornerstone" },
      { name: "Martin Davis", profession: "Assessment Tools", company: "Wonderlic" },
    ],
    topProfessionsNeeded: [
      { profession: "Automation Engineer", description: "For upskilling programs on new technology" },
      { profession: "Quality Consultant", description: "For quality training curriculum" },
      { profession: "Lean Consultant", description: "For lean training programs" },
    ],
    commitment: "Will connect you with my network of 50+ manufacturing HR directors",
    createdAt: daysAgo(150), updatedAt: daysAgo(12),
  },
  {
    id: "sphere-006", affiliateId: "aff-006", sphereName: "Supply Chain Excellence Group",
    members: [
      { name: "William Chen", profession: "Freight Broker", company: "C.H. Robinson" },
      { name: "Barbara Johnson", profession: "Customs Broker", company: "Livingston" },
      { name: "Charles Wilson", profession: "Warehouse Solutions", company: "Prologis" },
      { name: "Dorothy Lee", profession: "Inventory Software", company: "NetSuite" },
      { name: "Edward Martinez", profession: "Packaging Engineer", company: "Sonoco" },
      { name: "Frances Taylor", profession: "Trade Finance", company: "HSBC" },
      { name: "George Brown", profession: "Insurance - Cargo", company: "Chubb" },
      { name: "Hannah Davis", profession: "Sourcing Consultant", company: "Procurement Leaders" },
      { name: "Isaac White", profession: "Quality Auditor", company: "Intertek" },
      { name: "Julia Adams", profession: "Sustainability", company: "EcoVadis" },
    ],
    topProfessionsNeeded: [
      { profession: "Process Engineer", description: "For manufacturing process alignment" },
      { profession: "Digital Consultant", description: "For supply chain visibility tools" },
      { profession: "Quality Consultant", description: "For supplier quality programs" },
    ],
    commitment: "I'll introduce you to my network of 100+ procurement directors",
    createdAt: daysAgo(180), updatedAt: daysAgo(7),
  },
  {
    id: "sphere-007", affiliateId: "aff-007", sphereName: "Digital Manufacturing Innovators",
    members: [
      { name: "Nathan Park", profession: "Cloud Architect", company: "AWS" },
      { name: "Olivia Chen", profession: "Data Scientist", company: "SAS" },
      { name: "Peter Johnson", profession: "Cybersecurity", company: "CrowdStrike" },
      { name: "Quinn Williams", profession: "IoT Specialist", company: "PTC" },
      { name: "Rachel Martinez", profession: "MES Provider", company: "Rockwell" },
      { name: "Samuel Lee", profession: "ERP Consultant", company: "SAP" },
      { name: "Tina Brown", profession: "BI Analytics", company: "Tableau" },
      { name: "Ulysses Davis", profession: "Network Engineer", company: "Cisco" },
      { name: "Victoria White", profession: "Tech Recruiter", company: "Robert Half" },
      { name: "Walter Adams", profession: "IT Finance", company: "Dell Financial" },
    ],
    topProfessionsNeeded: [
      { profession: "Process Engineer", description: "For digitizing manufacturing processes" },
      { profession: "Lean Consultant", description: "For digital lean integration" },
      { profession: "Workforce Trainer", description: "For digital skills training" },
    ],
    commitment: "Happy to feature partners on my podcast and make tech introductions",
    createdAt: daysAgo(110), updatedAt: daysAgo(2),
  },
  {
    id: "sphere-008", affiliateId: "aff-008", sphereName: "Quality Management Professionals",
    members: [
      { name: "Xavier Chen", profession: "Calibration Services", company: "Tektronix" },
      { name: "Yvonne Johnson", profession: "Lab Services", company: "Element" },
      { name: "Zachary Williams", profession: "Document Control", company: "MasterControl" },
      { name: "Alice Martinez", profession: "Training Provider", company: "Exemplar Global" },
      { name: "Benjamin Lee", profession: "Audit Software", company: "iAuditor" },
      { name: "Cynthia Brown", profession: "Statistical Software", company: "Minitab" },
      { name: "Douglas Davis", profession: "Metrology", company: "Mitutoyo" },
      { name: "Eleanor White", profession: "Compliance Attorney", company: "Womble Bond" },
      { name: "Frederick Adams", profession: "Insurance - E&O", company: "Hartford" },
      { name: "Gloria Taylor", profession: "Industry Associations", company: "ASQ" },
    ],
    topProfessionsNeeded: [
      { profession: "Process Engineer", description: "For process capability studies" },
      { profession: "Automation Engineer", description: "For automated inspection" },
      { profession: "Supply Chain Consultant", description: "For supplier quality" },
    ],
    commitment: "Will refer all quality needs and provide mentoring to new consultants",
    createdAt: daysAgo(240), updatedAt: daysAgo(15),
  },
];

