/**
 * Mock One-to-One Meetings and Referrals for Affiliate Networking
 */

import type { OneToOneMeetingDoc, ReferralDoc, AffiliateStatsDoc } from "../schema";
import { daysAgo, daysFromNow, now } from "./affiliates";

// ============================================================================
// Sample One-to-One Meetings
// ============================================================================

export const mockOneToOneMeetings: OneToOneMeetingDoc[] = [
  {
    id: "meeting-001", initiatorId: "aff-001", partnerId: "aff-002",
    scheduledDate: daysFromNow(3), scheduledTime: "10:00 AM", duration: 60,
    meetingType: "in-person", location: "Starbucks on South Blvd, Charlotte",
    status: "confirmed",
    agendaItems: ["Review GAINS profiles", "Discuss ideal client profiles", "Identify referral opportunities"],
    worksheetsShared: true, svpReferralDiscussed: false, followUpCompleted: false, nextMeetingScheduled: false,
    matchScore: 85, matchReasons: ["Complementary services", "Same geographic area", "Shared client industries"],
    createdAt: daysAgo(5), updatedAt: daysAgo(1),
  },
  {
    id: "meeting-002", initiatorId: "aff-003", partnerId: "aff-004",
    scheduledDate: daysAgo(7), scheduledTime: "2:00 PM", duration: 60,
    meetingType: "virtual", virtualPlatform: "zoom", status: "completed",
    agendaItems: ["Lean before automation discussion", "Joint client opportunities"],
    worksheetsShared: true,
    meetingNotes: "Great synergy between lean and automation. Identified 3 joint opportunities.",
    shortTermReferralCommitment: "David to refer Lean Machine Shop for automation assessment",
    longTermReferralCommitment: "Jennifer to include David in all automation readiness discussions",
    svpReferralDiscussed: true, svpReferralDetails: "Discussed SVP V-Edge program for joint lean+automation assessments",
    followUpDate: daysFromNow(7), followUpCompleted: false,
    nextMeetingScheduled: true, nextMeetingDate: daysFromNow(30),
    matchScore: 92, matchReasons: ["Highly complementary services", "Process optimization synergy"],
    createdAt: daysAgo(14), updatedAt: daysAgo(7),
  },
  {
    id: "meeting-003", initiatorId: "aff-005", partnerId: "aff-001",
    scheduledDate: daysAgo(14), scheduledTime: "11:00 AM", duration: 60,
    meetingType: "in-person", location: "Panera Bread, Winston-Salem", status: "completed",
    worksheetsShared: true,
    meetingNotes: "Lisa can provide training for Sarah's process improvement clients. Sarah can refer manufacturers needing workforce development.",
    shortTermReferralCommitment: "Sarah to introduce Lisa to Blue Ridge Manufacturing",
    longTermReferralCommitment: "Quarterly check-ins on training needs",
    svpReferralDiscussed: true, svpReferralDetails: "SVP could bundle process consulting with workforce training",
    followUpDate: daysAgo(7), followUpCompleted: true, followUpNotes: "Introduction made, meeting scheduled",
    nextMeetingScheduled: true, nextMeetingDate: daysFromNow(14),
    matchScore: 78, matchReasons: ["Training complements process improvement", "Geographic proximity"],
    createdAt: daysAgo(21), updatedAt: daysAgo(7),
  },
  {
    id: "meeting-004", initiatorId: "aff-006", partnerId: "aff-002",
    scheduledDate: daysFromNow(5), scheduledTime: "9:00 AM", duration: 60,
    meetingType: "virtual", virtualPlatform: "teams", status: "scheduled",
    agendaItems: ["Supplier quality management", "ISO certification for supply chain"],
    worksheetsShared: false, svpReferralDiscussed: false, followUpCompleted: false, nextMeetingScheduled: false,
    matchScore: 88, matchReasons: ["Supply chain quality synergy", "Shared automotive clients"],
    createdAt: daysAgo(2), updatedAt: daysAgo(2),
  },
  {
    id: "meeting-005", initiatorId: "aff-007", partnerId: "aff-004",
    scheduledDate: daysAgo(3), scheduledTime: "3:00 PM", duration: 60,
    meetingType: "virtual", virtualPlatform: "google-meet", status: "completed",
    worksheetsShared: true,
    meetingNotes: "Amanda's digital transformation clients often need automation. David's automation clients need digital integration.",
    shortTermReferralCommitment: "Amanda to refer SmartFactory Inc for advanced automation",
    longTermReferralCommitment: "Joint Industry 4.0 webinar series",
    svpReferralDiscussed: true, svpReferralDetails: "SVP TwinEdge program perfect for digital+automation bundle",
    followUpDate: daysFromNow(3), followUpCompleted: false,
    nextMeetingScheduled: true, nextMeetingDate: daysFromNow(21),
    matchScore: 95, matchReasons: ["Industry 4.0 synergy", "Technology focus alignment", "Podcast collaboration opportunity"],
    createdAt: daysAgo(10), updatedAt: daysAgo(3),
  },
  {
    id: "meeting-006", initiatorId: "aff-008", partnerId: "aff-003",
    scheduledDate: daysFromNow(7), scheduledTime: "1:00 PM", duration: 60,
    meetingType: "in-person", location: "Greensboro Country Club", status: "confirmed",
    agendaItems: ["Quality + Lean synergy", "Mentoring opportunities", "Joint automotive clients"],
    worksheetsShared: true, svpReferralDiscussed: false, followUpCompleted: false, nextMeetingScheduled: false,
    matchScore: 82, matchReasons: ["Quality and lean complement each other", "Same city", "Mentoring interest"],
    createdAt: daysAgo(3), updatedAt: daysAgo(1),
  },
];

// ============================================================================
// Sample Referrals
// ============================================================================

export const mockReferrals: ReferralDoc[] = [
  {
    id: "ref-001", referrerId: "aff-001", referrerName: "Sarah Chen", recipientId: "aff-002", recipientName: "Michael Rodriguez",
    oneToOneMeetingId: "meeting-003", referralType: "short-term", commissionTier: "referral",
    prospectName: "John Harrison", prospectCompany: "Precision Parts Manufacturing",
    prospectEmail: "jharrison@precisionparts.com", prospectPhone: "704-555-1234", prospectTitle: "VP Operations",
    description: "Looking for ISO 9001 certification. Currently have no QMS in place.",
    whyGoodFit: "50-person shop, aerospace aspirations, budget approved for certification",
    isSvpReferral: false, status: "meeting-scheduled", estimatedValue: 35000,
    lastContactDate: daysAgo(2), contactAttempts: 2,
    createdAt: daysAgo(10), updatedAt: daysAgo(2),
  },
  {
    id: "ref-002", referrerId: "aff-003", referrerName: "David Kim", recipientId: "aff-004", recipientName: "Jennifer Park",
    oneToOneMeetingId: "meeting-002", referralType: "short-term", commissionTier: "assist",
    prospectName: "Maria Gonzalez", prospectCompany: "Lean Machine Shop",
    prospectEmail: "mgonzalez@leanmachine.com", prospectPhone: "336-555-5678", prospectTitle: "Owner",
    description: "Completed lean transformation, now ready for automation. Looking at CNC machine tending.",
    whyGoodFit: "Already lean, good cash flow, expanding capacity",
    isSvpReferral: true, svpServiceInterest: ["V-Edge Assessment", "Automation Readiness"],
    status: "proposal", dealValue: 75000, estimatedValue: 75000,
    lastContactDate: daysAgo(1), contactAttempts: 3,
    createdAt: daysAgo(7), updatedAt: daysAgo(1),
  },
  {
    id: "ref-003", referrerId: "aff-002", referrerName: "Michael Rodriguez", recipientId: "aff-003", recipientName: "David Kim",
    referralType: "long-term", commissionTier: "referral",
    prospectName: "Robert Chen", prospectCompany: "Quality Castings Inc",
    prospectEmail: "rchen@qualitycastings.com", prospectPhone: "919-555-9012", prospectTitle: "Plant Manager",
    description: "Just achieved ISO certification, now wants to improve efficiency. High scrap rates.",
    whyGoodFit: "Quality foundation in place, management committed to improvement",
    isSvpReferral: false, status: "contacted", estimatedValue: 45000,
    lastContactDate: daysAgo(5), contactAttempts: 1,
    createdAt: daysAgo(14), updatedAt: daysAgo(5),
  },
  {
    id: "ref-004", referrerId: "aff-007", referrerName: "Lisa Wang", recipientId: "aff-005", recipientName: "James Wilson",
    oneToOneMeetingId: "meeting-005", referralType: "short-term", commissionTier: "co-sell",
    prospectName: "Susan Park", prospectCompany: "DataDriven Manufacturing",
    prospectEmail: "spark@datadrivenmfg.com", prospectPhone: "919-555-3456", prospectTitle: "HR Director",
    description: "Implementing new MES system, need to train 200 operators on digital tools.",
    whyGoodFit: "Budget allocated, timeline is 3 months, executive sponsorship",
    isSvpReferral: true, svpServiceInterest: ["IntellEdge", "Workforce Digital Readiness"],
    status: "won", dealValue: 45000, estimatedValue: 45000, dealClosedDate: daysAgo(3),
    lastContactDate: daysAgo(3), contactAttempts: 4,
    createdAt: daysAgo(21), updatedAt: daysAgo(3),
  },
  {
    id: "ref-005", referrerId: "aff-004", referrerName: "Jennifer Park", recipientId: "aff-006", recipientName: "Robert Martinez",
    referralType: "long-term", commissionTier: "assist",
    prospectName: "William Thompson", prospectCompany: "AutoAssembly Corp",
    prospectEmail: "wthompson@autoassembly.com", prospectPhone: "704-555-7890", prospectTitle: "Supply Chain Director",
    description: "Automation project revealed supply chain vulnerabilities. Need help with supplier diversification.",
    whyGoodFit: "Urgent need, C-suite attention, budget available",
    isSvpReferral: false, status: "negotiation", dealValue: 120000, estimatedValue: 120000,
    lastContactDate: daysAgo(1), contactAttempts: 5,
    createdAt: daysAgo(30), updatedAt: daysAgo(1),
  },
  {
    id: "ref-006", referrerId: "aff-006", referrerName: "Robert Martinez", recipientId: "aff-007", recipientName: "Lisa Wang",
    referralType: "short-term", commissionTier: "co-sell",
    prospectName: "Emily Watson", prospectCompany: "GlobalSource Manufacturing",
    prospectEmail: "ewatson@globalsource.com", prospectPhone: "704-555-2345", prospectTitle: "CIO",
    description: "Need supply chain visibility software. Want to track inventory across 5 locations.",
    whyGoodFit: "Digital initiative funded, timeline Q1, decision maker engaged",
    isSvpReferral: true, svpServiceInterest: ["TwinEdge", "Digital Supply Chain"],
    status: "proposal", dealValue: 85000, estimatedValue: 85000,
    lastContactDate: daysAgo(2), contactAttempts: 3,
    createdAt: daysAgo(12), updatedAt: daysAgo(2),
  },
];

// ============================================================================
// Affiliate Stats
// ============================================================================

export const mockAffiliateStats: AffiliateStatsDoc[] = [
  {
    id: "stats-001", affiliateId: "aff-001",
    biographyComplete: true, gainsProfileComplete: true, contactSphereComplete: true, customersListComplete: true,
    profileCompletionPercent: 100,
    totalOneToOnesScheduled: 24, totalOneToOnesCompleted: 22, oneToOnesThisMonth: 3, oneToOnesThisQuarter: 8,
    lastOneToOneDate: daysAgo(7),
    referralsGiven: 18, referralsReceived: 15, referralsGivenThisMonth: 2, referralsReceivedThisMonth: 3,
    dealsClosedFromReferralsGiven: 8, dealsClosedFromReferralsReceived: 6,
    totalRevenueGenerated: 425000, totalRevenueReceived: 380000,
    svpReferralsGiven: 5, svpReferralsClosed: 3, svpRevenueGenerated: 175000,
    engagementScore: 92, currentOneToOneStreak: 8, longestOneToOneStreak: 12,
    updatedAt: now(),
  },
  {
    id: "stats-002", affiliateId: "aff-002",
    biographyComplete: true, gainsProfileComplete: true, contactSphereComplete: true, customersListComplete: true,
    profileCompletionPercent: 100,
    totalOneToOnesScheduled: 30, totalOneToOnesCompleted: 28, oneToOnesThisMonth: 4, oneToOnesThisQuarter: 10,
    lastOneToOneDate: daysAgo(3),
    referralsGiven: 25, referralsReceived: 22, referralsGivenThisMonth: 3, referralsReceivedThisMonth: 2,
    dealsClosedFromReferralsGiven: 12, dealsClosedFromReferralsReceived: 10,
    totalRevenueGenerated: 580000, totalRevenueReceived: 520000,
    svpReferralsGiven: 8, svpReferralsClosed: 5, svpRevenueGenerated: 245000,
    engagementScore: 98, currentOneToOneStreak: 15, longestOneToOneStreak: 15,
    updatedAt: now(),
  },
  {
    id: "stats-003", affiliateId: "aff-003",
    biographyComplete: true, gainsProfileComplete: true, contactSphereComplete: true, customersListComplete: true,
    profileCompletionPercent: 100,
    totalOneToOnesScheduled: 20, totalOneToOnesCompleted: 18, oneToOnesThisMonth: 2, oneToOnesThisQuarter: 6,
    lastOneToOneDate: daysAgo(14),
    referralsGiven: 14, referralsReceived: 12, referralsGivenThisMonth: 1, referralsReceivedThisMonth: 2,
    dealsClosedFromReferralsGiven: 6, dealsClosedFromReferralsReceived: 5,
    totalRevenueGenerated: 320000, totalRevenueReceived: 275000,
    svpReferralsGiven: 4, svpReferralsClosed: 2, svpRevenueGenerated: 95000,
    engagementScore: 85, currentOneToOneStreak: 6, longestOneToOneStreak: 10,
    updatedAt: now(),
  },
  {
    id: "stats-004", affiliateId: "aff-004",
    biographyComplete: true, gainsProfileComplete: true, contactSphereComplete: true, customersListComplete: true,
    profileCompletionPercent: 100,
    totalOneToOnesScheduled: 28, totalOneToOnesCompleted: 26, oneToOnesThisMonth: 3, oneToOnesThisQuarter: 9,
    lastOneToOneDate: daysAgo(5),
    referralsGiven: 22, referralsReceived: 20, referralsGivenThisMonth: 2, referralsReceivedThisMonth: 3,
    dealsClosedFromReferralsGiven: 10, dealsClosedFromReferralsReceived: 9,
    totalRevenueGenerated: 680000, totalRevenueReceived: 590000,
    svpReferralsGiven: 6, svpReferralsClosed: 4, svpRevenueGenerated: 285000,
    engagementScore: 94, currentOneToOneStreak: 11, longestOneToOneStreak: 14,
    updatedAt: now(),
  },
  {
    id: "stats-005", affiliateId: "aff-005",
    biographyComplete: true, gainsProfileComplete: true, contactSphereComplete: false, customersListComplete: true,
    profileCompletionPercent: 85,
    totalOneToOnesScheduled: 16, totalOneToOnesCompleted: 14, oneToOnesThisMonth: 2, oneToOnesThisQuarter: 5,
    lastOneToOneDate: daysAgo(10),
    referralsGiven: 10, referralsReceived: 12, referralsGivenThisMonth: 1, referralsReceivedThisMonth: 2,
    dealsClosedFromReferralsGiven: 4, dealsClosedFromReferralsReceived: 5,
    totalRevenueGenerated: 185000, totalRevenueReceived: 225000,
    svpReferralsGiven: 3, svpReferralsClosed: 2, svpRevenueGenerated: 90000,
    engagementScore: 76, currentOneToOneStreak: 4, longestOneToOneStreak: 8,
    updatedAt: now(),
  },
  {
    id: "stats-006", affiliateId: "aff-006",
    biographyComplete: true, gainsProfileComplete: true, contactSphereComplete: true, customersListComplete: true,
    profileCompletionPercent: 100,
    totalOneToOnesScheduled: 22, totalOneToOnesCompleted: 20, oneToOnesThisMonth: 3, oneToOnesThisQuarter: 7,
    lastOneToOneDate: daysAgo(8),
    referralsGiven: 16, referralsReceived: 14, referralsGivenThisMonth: 2, referralsReceivedThisMonth: 1,
    dealsClosedFromReferralsGiven: 7, dealsClosedFromReferralsReceived: 6,
    totalRevenueGenerated: 520000, totalRevenueReceived: 410000,
    svpReferralsGiven: 4, svpReferralsClosed: 2, svpRevenueGenerated: 140000,
    engagementScore: 88, currentOneToOneStreak: 7, longestOneToOneStreak: 11,
    updatedAt: now(),
  },
  {
    id: "stats-007", affiliateId: "aff-007",
    biographyComplete: true, gainsProfileComplete: true, contactSphereComplete: true, customersListComplete: true,
    profileCompletionPercent: 100,
    totalOneToOnesScheduled: 18, totalOneToOnesCompleted: 17, oneToOnesThisMonth: 3, oneToOnesThisQuarter: 8,
    lastOneToOneDate: daysAgo(3),
    referralsGiven: 15, referralsReceived: 18, referralsGivenThisMonth: 2, referralsReceivedThisMonth: 3,
    dealsClosedFromReferralsGiven: 7, dealsClosedFromReferralsReceived: 8,
    totalRevenueGenerated: 380000, totalRevenueReceived: 450000,
    svpReferralsGiven: 6, svpReferralsClosed: 4, svpRevenueGenerated: 210000,
    engagementScore: 91, currentOneToOneStreak: 9, longestOneToOneStreak: 9,
    updatedAt: now(),
  },
  {
    id: "stats-008", affiliateId: "aff-008",
    biographyComplete: true, gainsProfileComplete: true, contactSphereComplete: true, customersListComplete: true,
    profileCompletionPercent: 100,
    totalOneToOnesScheduled: 35, totalOneToOnesCompleted: 33, oneToOnesThisMonth: 2, oneToOnesThisQuarter: 6,
    lastOneToOneDate: daysAgo(12),
    referralsGiven: 30, referralsReceived: 18, referralsGivenThisMonth: 2, referralsReceivedThisMonth: 1,
    dealsClosedFromReferralsGiven: 15, dealsClosedFromReferralsReceived: 8,
    totalRevenueGenerated: 720000, totalRevenueReceived: 380000,
    svpReferralsGiven: 7, svpReferralsClosed: 4, svpRevenueGenerated: 195000,
    engagementScore: 82, currentOneToOneStreak: 3, longestOneToOneStreak: 18,
    updatedAt: now(),
  },
];

